### ISSUE TITLE
Suggestion: Switch to https://github.com/gofrs/uuid

### ISSUE THREAD

**Issue by adrianliechti** [microsoft/ApplicationInsights-Go#27]
you might want to switch your UUID library

see
https://github.com/gofrs/uuid
https://github.com/satori/go.uuid/pull/75

your friends at the AKS engine did as well
https://github.com/Azure/aks-engine/pull/466

cheers

**Comment by tandr** [comment]
We have switched to `github.com/google/uuid` https://github.com/google/uuid seems to be maintained, but I am not sure if Microsoft is allowed to use Google's code.

**Comment by jjjordanmsft** [comment]
iirc, `google/uuid` was marked unstable back when `satori/go.uuid` broke everything so I hesitated to move then.  There's nothing preventing me from referencing either as long as they're BSD-licensed.  We are using the Go standard library, after all.

I'll also have a look at gofrs.  It's probably the most straightforward option.  I think I want to keep the hacky `uuid.go` stuff because it's used in some contexts that are not really situated to handle errors.

**Comment by tandr** [comment]
To think of it... How about having a hook (register a function) that allows users to specify `func() string` that returns uuid ? This way everybody will use the one that is already used in the app. The mechanism could be similar to what `sql` package uses for registration
Why the heck uuid generation is not a part of standard library is beyond me...

**Comment by kwontae** [comment]
So why was this closed without switching to https://github.com/gofrs/uuid? This is a forked but maintained repo unlike the satori repo

**Comment by kwontae** [comment]
@adrianliechti
